fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.17.1"
    java:
      repo: "https://github.com/puppetlabs/puppetlabs-java.git"
      ref: "1.6.0"
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive.git"
      ref: "v1.3.0"
    fetchtool:
      repo: "https://github.com/coi-gov-pl/puppet-fetchtool.git"
      ref: "v1.0.0"
