---
language: ruby
  - rvm: '2.1'
  - rvm: '2.3'
sudo: false
bundler_args: --without development --jobs=3 --retry=3 --no-deployment
cache: bundler
script:
  - bundle exec rake test
notifications:
email: false
